# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='condition',
            field=models.CharField(default='none', max_length=240),
        ),
    ]
