# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-20 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='condition',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
